# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=256)),
                ('wen', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
                ('said1', models.CharField(max_length=50)),
                ('said2', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('title', models.CharField(max_length=30)),
                ('html', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=256)),
                ('wen', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
                ('said1', models.CharField(max_length=50)),
                ('said2', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('price_good', models.DecimalField(decimal_places=4, max_digits=10)),
                ('title', models.CharField(max_length=30)),
                ('html', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=256)),
                ('wen', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
                ('said1', models.CharField(max_length=50)),
                ('said2', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('price_good', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_tel', models.CharField(max_length=20)),
                ('good_id', models.IntegerField(default=0)),
                ('img', models.CharField(max_length=256)),
                ('wen', models.CharField(max_length=100)),
                ('said1', models.CharField(max_length=50)),
                ('said2', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('num', models.IntegerField()),
                ('price_good', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=256)),
                ('wen', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
                ('said1', models.CharField(max_length=50)),
                ('said2', models.CharField(max_length=50)),
                ('price_good', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='lunbo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=256)),
                ('wen', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lunbo1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=256)),
                ('wen', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
                ('said1', models.CharField(max_length=50)),
                ('said2', models.CharField(max_length=50)),
                ('div', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='One',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=256)),
                ('wen', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
                ('said1', models.CharField(max_length=50)),
                ('said2', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('title', models.CharField(max_length=30)),
                ('html', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_tel', models.CharField(max_length=20)),
                ('u_password', models.CharField(max_length=256)),
                ('u_isdel', models.BooleanField(default=False)),
                ('u_token', models.CharField(default='', max_length=256)),
                ('u_img', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='g_user',
            field=models.ManyToManyField(null=True, to='app.User'),
        ),
    ]
