# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-09 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscar',
            name='isselect',
            field=models.BooleanField(default=True),
        ),
    ]
