# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsBuyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_tel', models.CharField(max_length=20)),
                ('good_id', models.IntegerField(default=0)),
                ('img', models.CharField(max_length=256)),
                ('wen', models.CharField(max_length=100)),
                ('said1', models.CharField(max_length=50)),
                ('said2', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('num_all', models.IntegerField()),
                ('price_good', models.DecimalField(decimal_places=4, max_digits=10)),
                ('price_all', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
