# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_goodscar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_img',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
